version: 2.1
default: &defaults
  docker:
    - image: node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit
      - run:
          when: on_fail
          command: npm audit fix


workflows:
  my_test_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
