version: 2.1
default: &defaults
  docker:
    - image: node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit
workflows:
  my_test_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
